name: Meaningcloud Java SDK tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build docker tests image
        shell: sh
        working-directory: .
        run: docker build -t meaningcloud_java_sdk_tests -f docker/Dockerfile .
      - name: Running docker image
        env:
          DMEANINGCLOUD_KEY: ${{ secrets.DMEANINGCLOUD_KEY }}
        run: docker run -e DMEANINGCLOUD_KEY meaningcloud_java_sdk_tests
      - name: Getting reports from docker container
        run: DOCKER_ID=$(docker ps -a | grep 'java_sdk_tests' | awk '{ print $1 }') && docker cp $DOCKER_ID:/tmp . && ls
      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: tmp/html/*
      #- name: Run tests checker 
      #  uses: check-run-reporter/action@v2.0.0
      #  # always run, otherwise you'll only see results for passing builds
      #  if: ${{ always() }}
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    report: 'tmp/xml/*.xml'
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Meaningcloud JAVA SDK Test Results
          files: tmp/xml/*.xml
