name: Meaningcloud Java SDK tests

on: [push]

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
      - name: Build docker tests image
        run: docker build -t meaningcloud_java_sdk_tests -f docker/Dockerfile . && echo "correct"